In [2]:
import numpy as np

from sympy import *
init_printing(use_latex=True)

import scipy.spatial.distance as ssd
import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
x = np.array([1,1])
print(x)
y = np.array([0.5,1.5])
print(y)

[1 1]
[0.5 1.5]


In [4]:
np.sqrt(np.sum(pow(x-y,2.0)))

In [5]:
ssd.euclidean(x,y)

In [7]:
print('Euclidean: %f'%ssd.minkowski(x,y,2))
print('Manhattan: %f'%ssd.minkowski(x,y,1))


Euclidean: 0.707107
Manhattan: 1.000000


In [9]:
np.sum(x*y)/(np.sqrt(np.dot(x,x))*np.sqrt(np.dot(y,y)))

In [10]:
print('Cosine similarity: %f'%(np.dot(x,y) /
(np.sqrt(np.dot(x,x)) * np.sqrt(np.dot(y,y)))))
print('Cosine distance: %f'%ssd.cosine(x,y))

Cosine similarity: 0.894427
Cosine distance: 0.105573


In [11]:
print(np.sum(x*y))
print(np.dot(x,y))

2.0
2.0


In [12]:
# Make another vector
z = np.array([1.5,0.25])
# Combine all vectors -by row- to form a matrix
data = np.array([x,y,z])
data

array([[1.  , 1.  ],
       [0.5 , 1.5 ],
       [1.5 , 0.25]])

In [13]:
Matrix(data)

⎡1.0  1.0 ⎤
⎢         ⎥
⎢0.5  1.5 ⎥
⎢         ⎥
⎣1.5  0.25⎦

In [14]:
Matrix(x)

⎡1⎤
⎢ ⎥
⎣1⎦

In [15]:
Matrix(x).T


[1  1]

In [16]:
ssd.squareform(ssd.pdist(data,metric='euclidean'))

array([[0.        , 0.70710678, 0.90138782],
       [0.70710678, 0.        , 1.60078106],
       [0.90138782, 1.60078106, 0.        ]])

In [17]:
ssd.squareform(ssd.pdist(data,metric='minkowski',p=2))

array([[0.        , 0.70710678, 0.90138782],
       [0.70710678, 0.        , 1.60078106],
       [0.90138782, 1.60078106, 0.        ]])

In [18]:
ssd.squareform(ssd.pdist(data,metric='minkowski',p=1))

array([[0.  , 1.  , 1.25],
       [1.  , 0.  , 2.25],
       [1.25, 2.25, 0.  ]])

In [19]:
ssd.squareform(ssd.pdist(data,metric='cosine'))

array([[0.        , 0.10557281, 0.18626653],
       [0.10557281, 0.        , 0.53211228],
       [0.18626653, 0.53211228, 0.        ]])

In [20]:
Matrix(ssd.squareform(ssd.pdist(data,metric='cosine')))

⎡       0.0         0.105572809000084  0.186266528793265⎤
⎢                                                       ⎥
⎢0.105572809000084         0.0         0.532112279580967⎥
⎢                                                       ⎥
⎣0.186266528793265  0.532112279580967         0.0       ⎦

In [21]:
Eq(Mul(Matrix(data),Matrix(x),evaluate=False),
Matrix(np.dot(data,x)),evaluate=False)

⎡1.0  1.0 ⎤       ⎡2.0 ⎤
⎢         ⎥ ⎡1⎤   ⎢    ⎥
⎢0.5  1.5 ⎥⋅⎢ ⎥ = ⎢2.0 ⎥
⎢         ⎥ ⎣1⎦   ⎢    ⎥
⎣1.5  0.25⎦       ⎣1.75⎦

In [22]:
np.dot(data,x)

array([2.  , 2.  , 1.75])

In [23]:
Matrix(np.dot(data,x))

⎡2.0 ⎤
⎢    ⎥
⎢2.0 ⎥
⎢    ⎥
⎣1.75⎦

In [24]:
np.dot(x,data) #the matrix cannot be computed because the two attempting to be computed are
               #are not the proper size

ValueError: shapes (2,) and (3,2) not aligned: 2 (dim 0) != 3 (dim 0)

In [25]:
Eq(Mul(Matrix(data),Matrix(data).T,evaluate=False),
Matrix(np.dot(data,data.T)),evaluate=False)

⎡1.0  1.0 ⎤                    ⎡2.0    2.0    1.75 ⎤
⎢         ⎥ ⎡1.0  0.5  1.5 ⎤   ⎢                   ⎥
⎢0.5  1.5 ⎥⋅⎢              ⎥ = ⎢2.0    2.5   1.125 ⎥
⎢         ⎥ ⎣1.0  1.5  0.25⎦   ⎢                   ⎥
⎣1.5  0.25⎦                    ⎣1.75  1.125  2.3125⎦

In [26]:
Matrix(np.dot(data,data.T))

⎡2.0    2.0    1.75 ⎤
⎢                   ⎥
⎢2.0    2.5   1.125 ⎥
⎢                   ⎥
⎣1.75  1.125  2.3125⎦

In [27]:
def mynorm(a_vector):
    return np.sqrt(np.dot(a_vector, a_vector))

A = np.round(
    1.0 - (np.dot(data,data.T) / np.dot(
    np.reshape(np.apply_along_axis(mynorm,1,data),[3,1]),
    np.reshape(np.apply_along_axis(mynorm,1,data),[1,3]))),12)
Matrix(A)

⎡     0.0         0.105572809    0.186266528793⎤
⎢                                              ⎥
⎢ 0.105572809         0.0        0.532112279581⎥
⎢                                              ⎥
⎣0.186266528793  0.532112279581       0.0      ⎦

In [28]:
L,Q = np.linalg.eig(A)

Mul(Matrix(Q),Matrix(np.diag(L)), Matrix(Q).T,evaluate = False)

⎡0.325098539559343  0.938831137274348   -0.113609133702079⎤ ⎡0.603064244356408
⎢                                                         ⎥ ⎢                 
⎢0.657042235063221  -0.310640328350735  -0.686875598449439⎥⋅⎢       0.0       
⎢                                                         ⎥ ⎢                 
⎣0.680151777855141  -0.148656254783652  0.717840425856742 ⎦ ⎣       0.0       

         0.0                 0.0        ⎤ ⎡0.325098539559343   0.6570422350632
                                        ⎥ ⎢                                   
  -0.064425703636322         0.0        ⎥⋅⎢0.938831137274348   -0.310640328350
                                        ⎥ ⎢                                   
         0.0          -0.538638540720086⎦ ⎣-0.113609133702079  -0.686875598449

21   0.680151777855141 ⎤
                       ⎥
735  -0.148656254783652⎥
                       ⎥
439  0.717840425856742 ⎦

In [30]:
Matrix(np.round(np.dot(np.dot(Q,np.diag(L)),Q.T),12))

⎡     0.0         0.105572809    0.186266528793⎤
⎢                                              ⎥
⎢ 0.105572809         0.0        0.532112279581⎥
⎢                                              ⎥
⎣0.186266528793  0.532112279581       0.0      ⎦

In [31]:
U,S,V = np.linalg.svd(A,full_matrices=True)
Mul(Matrix(U),Matrix(np.diag(S)),Matrix(V),evaluate=False)

⎡0.325098539559343  -0.113609133702079  0.938831137274348 ⎤ ⎡0.603064244356408
⎢                                                         ⎥ ⎢                 
⎢0.657042235063221  -0.686875598449439  -0.310640328350735⎥⋅⎢       0.0       
⎢                                                         ⎥ ⎢                 
⎣0.680151777855141  0.717840425856742   -0.148656254783652⎦ ⎣       0.0       

         0.0                0.0        ⎤ ⎡0.325098539559343   0.65704223506322
                                       ⎥ ⎢                                    
  0.538638540720086         0.0        ⎥⋅⎢0.113609133702079   0.68687559844943
                                       ⎥ ⎢                                    
         0.0         0.0644257036363219⎦ ⎣-0.938831137274348  0.31064032835073

1  0.680151777855141 ⎤
                     ⎥
9  -0.717840425856741⎥
                     ⎥
5  0.148656254783653 ⎦

In [32]:
Matrix(np.round(np.dot(np.dot(U,np.diag(S)),V),12))

⎡     0.0         0.105572809    0.186266528793⎤
⎢                                              ⎥
⎢ 0.105572809         0.0        0.532112279581⎥
⎢                                              ⎥
⎣0.186266528793  0.532112279581       0.0      ⎦